"""Chinese (in-game) -> optimizer key mappings for echoes, sonata sets and stats.

Data lives in ``echo_data.json`` next to this module (generated by joining the
optimizer's ``src/echoes/index.ts`` with Chinese names from the Wuthering Waves
wiki). Regenerate with scratch/converter/fetch_zh2.py + the join step.
"""
from __future__ import annotations

import json
import os

_DATA_PATH = os.path.join(os.path.dirname(__file__), "echo_data.json")

with open(_DATA_PATH, encoding="utf-8") as _f:
    _DATA = json.load(_f)

# zh echo name -> {"key": str, "cost": int, "sets": [str, ...]}
ECHO_BY_ZH: dict[str, dict] = dict(_DATA["echo_name_zh_to_key"])
# traditional-Chinese echo name -> key (fallback for zh_TW clients)
ECHO_BY_ZHT: dict[str, str] = dict(_DATA.get("echo_name_zht_to_key", {}))
# zh sonata set name -> optimizer set key
SET_BY_ZH: dict[str, str] = dict(_DATA["set_name_zh_to_key"])
# ordered list of (zh substring, optimizer stat key); MUST be longest/most
# specific first so substring matching is unambiguous.
STAT_SUBSTRINGS: list[tuple[str, str]] = [tuple(p) for p in _DATA["stat_map"]]
# stat keys that have a flat variant (ATK/HP/DEF -> *_FLAT when not a percent)
FLAT_CAPABLE: set[str] = set(_DATA["flat_capable"])


# "Phantom" echoes are cosmetic recolors prefixed with 异相/異相; they are the
# same echo as their (possibly Nightmare-prefixed) base for optimizer purposes.
_PHANTOM_PREFIXES = ("异相", "異相")
# Middle-dot separator variants the game/wiki/OCR use interchangeably (and OCR
# sometimes drops entirely) — removed during normalization.
_SEP_CHARS = "・•·･·· "

# Known OCR misreads of echo-name characters (extend as new ones are observed).
_NAME_TEXT_FIXES = {
    "梦魔意": "梦魇",  # 魇 sometimes OCRs as 魔意
    "梦魔": "梦魇",
}

# Echoes missing from the auto-generated wiki join (cost/sets from the
# optimizer's echo data). Three groups, by confidence:
#   1. CONFIRMED in-game (seen in captured screenshots).
#   2. HIGH — Chinese name from the wiki "Other Languages" template.
#   3. BEST-EFFORT — Reminiscence (共鸣回响) name derived from the boss's wiki
#      Chinese name; the exact in-game form is unverified, so if it doesn't
#      match the parser falls back to echo=null (harmless). Fix when observed.
_MANUAL_ECHO_ZH = {
    # 1. confirmed in-game
    "共鸣回响达妮娅": {"key": "ReminiscenceDenia", "cost": 4, "sets": ["ChromaticFoam"]},
    "共鸣回响梦魇亚当": {"key": "ReminiscenceNightmareAdamSmasher", "cost": 4,
                       "sets": ["ShadowofShatteredDreams"]},
    # 2. high confidence (wiki Other Languages)
    "残星·重锤造匠": {"key": "FractsidusThruster", "cost": 3,
                     "sets": ["EternalRadiance", "EmpyreanAnthem"]},
    "嚣风戏猿": {"key": "Hoochief", "cost": 3, "sets": ["SierraGale", "RejuvenatingGlow"]},
    "抛石幼猿": {"key": "Hooscamp", "cost": 1, "sets": ["SierraGale", "LingeringTunes"]},
    # 3. best-effort (共鸣回响 + boss wiki zh; in-game form unverified)
    "共鸣回响芬莱克麦克白": {"key": "ReminiscenceFenrico", "cost": 4,
                          "sets": ["DreamoftheLost", "LawofHarmony"]},
    "共鸣回响芬莱克": {"key": "ReminiscenceFenrico", "cost": 4,
                     "sets": ["DreamoftheLost", "LawofHarmony"]},
    "共鸣回响芙露德莉斯": {"key": "ReminiscenceFleurdelys", "cost": 4,
                        "sets": ["GustsofWelkin", "WindwardPilgrimage"]},
    "共鸣回响冠顶苍隼": {"key": "ReminiscenceKronaclaw", "cost": 3,
                      "sets": ["TrailblazingStar", "ChromaticFoam"]},
    "共鸣回响利维亚坦": {"key": "ReminiscenceThrenodianLeviathan", "cost": 4,
                      "sets": ["FlamewingsShadow", "ThreadofSeveredFate"]},
    # still unmapped (no wiki zh): Glommoth, VoidwingMoth,
    # ReminiscenceThrenodianVoidborneConstruct -> export with echo=null + warning.
}


def _norm_name(s: str) -> str:
    """Normalize an echo name for matching: drop separators/spaces, fix garbles."""
    s = (s or "").strip()
    for bad, good in _NAME_TEXT_FIXES.items():
        s = s.replace(bad, good)
    for sep in _SEP_CHARS:
        s = s.replace(sep, "")
    return s


# Separator-insensitive index so 梦魇·X / 梦魇・X / 梦魇X all match.
# (Traditional-Chinese names are resolved separately in _exact_echo.)
_NORM_ECHO_INDEX = {_norm_name(k): v for k, v in ECHO_BY_ZH.items()}
_NORM_ECHO_INDEX.update({_norm_name(k): v for k, v in _MANUAL_ECHO_ZH.items()})


def _exact_echo(name: str) -> dict | None:
    n = _norm_name(name)
    if n in _NORM_ECHO_INDEX:
        return _NORM_ECHO_INDEX[n]
    if name in ECHO_BY_ZHT:
        key = ECHO_BY_ZHT[name]
        for v in ECHO_BY_ZH.values():
            if v["key"] == key:
                return v
    return None


def lookup_echo(zh_name: str) -> dict | None:
    """Return ``{"key", "cost", "sets"}`` for a Chinese echo name, or None.

    Tolerates middle-dot separator variants and known OCR garbles, and handles
    the 异相 (Phantom) cosmetic prefix by stripping only that prefix and matching
    the canonical base name (e.g. ``异相·梦魇·无冠者`` -> ``梦魇·无冠者`` ->
    NightmareCrownless), keeping Nightmare/Phantom variants distinct.
    """
    name = (zh_name or "").strip()
    hit = _exact_echo(name)
    if hit is not None:
        return hit
    norm = _norm_name(name)
    for prefix in _PHANTOM_PREFIXES:
        if norm.startswith(prefix):
            hit = _exact_echo(norm[len(prefix):])
            if hit is not None:
                return hit
    return None


def lookup_set(zh_name: str) -> str | None:
    """Return the optimizer set key for a Chinese sonata name, or None."""
    return SET_BY_ZH.get((zh_name or "").strip())


def map_stat(zh_text: str, value_str: str) -> str | None:
    """Map a Chinese stat label + its value string to an optimizer stat key.

    ATK/HP/DEF become ``*_FLAT`` when the value is not a percentage.
    """
    text = (zh_text or "").strip()
    key = None
    for sub, k in STAT_SUBSTRINGS:
        if sub in text:
            key = k
            break
    if key is None:
        return None
    if key in FLAT_CAPABLE:
        is_percent = "%" in value_str or "％" in value_str
        if not is_percent:
            key = f"{key}_FLAT"
    return key
